[2025-02-20T19:31:25.276+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: listenbrainz_pipeline_duckdb.create_schema manual__2025-02-20T19:26:21.854176+00:00 [queued]>
[2025-02-20T19:31:25.288+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: listenbrainz_pipeline_duckdb.create_schema manual__2025-02-20T19:26:21.854176+00:00 [queued]>
[2025-02-20T19:31:25.289+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-02-20T19:31:25.289+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2025-02-20T19:31:25.289+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-02-20T19:31:25.311+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_schema> on 2025-02-20 19:26:21.854176+00:00
[2025-02-20T19:31:25.318+0000] {standard_task_runner.py:55} INFO - Started process 268 to run task
[2025-02-20T19:31:25.321+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'listenbrainz_pipeline_duckdb', 'create_schema', 'manual__2025-02-20T19:26:21.854176+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/listenbrainz_dag.py', '--cfg-path', '/tmp/tmp5iz0_pcq']
[2025-02-20T19:31:25.323+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask create_schema
[2025-02-20T19:31:25.414+0000] {task_command.py:388} INFO - Running <TaskInstance: listenbrainz_pipeline_duckdb.create_schema manual__2025-02-20T19:26:21.854176+00:00 [running]> on host 7ca98136cacf
[2025-02-20T19:31:25.517+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=listenbrainz_pipeline_duckdb
AIRFLOW_CTX_TASK_ID=create_schema
AIRFLOW_CTX_EXECUTION_DATE=2025-02-20T19:26:21.854176+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-20T19:26:21.854176+00:00
[2025-02-20T19:31:25.547+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/listenbrainz_dag.py", line 37, in create_schema
    engine = create_engine(DB_URL, future=True)
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 522, in create_engine
    entrypoint = u._get_entrypoint()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 662, in _get_entrypoint
    cls = registry.load(name)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 344, in load
    "Can't load plugin: %s:%s" % (self.group, name)
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:duckdb
[2025-02-20T19:31:25.562+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=listenbrainz_pipeline_duckdb, task_id=create_schema, execution_date=20250220T192621, start_date=20250220T193125, end_date=20250220T193125
[2025-02-20T19:31:25.577+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task create_schema (Can't load plugin: sqlalchemy.dialects:duckdb; 268)
[2025-02-20T19:31:25.613+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-02-20T19:31:25.673+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
